version: '3.8'

services:
  web_middle:
    image: nginx
    container_name: web_middle
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - web_data:/usr/share/nginx/html
    networks:
      - middle_net

volumes:
  web_data:
    external: true

networks:
  middle_net:
    external: true